import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import { TEKDUZEN_HESAP_PLANI } from "./chart-of-accounts.js";
import { tenants, users, fiscalYears, accounts } from "../schema/index.js";
import { randomUUID } from "crypto";

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) {
  console.error("DATABASE_URL ortam değişkeni gereklidir");
  process.exit(1);
}

async function seed() {
  const client = postgres(DATABASE_URL!);
  const db = drizzle(client);

  console.log("🌱 Seed başlatılıyor...");

  // 1. Demo tenant oluştur
  const tenantId = randomUUID();
  await db.insert(tenants).values({
    id: tenantId,
    name: "Demo Şirket A.Ş.",
    taxId: "1234567890",
    taxOffice: "Büyük Mükellefler",
    address: "Atatürk Cad. No: 123",
    city: "İstanbul",
    district: "Şişli",
    phone: "02121234567",
    email: "info@demosirket.com",
  });
  console.log("✅ Demo tenant oluşturuldu");

  // 2. Admin kullanıcı oluştur (şifre: Admin123456!!)
  // Argon2id hash for "Admin123456!!" - real hash will be generated by backend
  await db.insert(users).values({
    id: randomUUID(),
    tenantId,
    email: "admin@finbooks.local",
    name: "Sistem Yöneticisi",
    passwordHash: "$argon2id$v=19$m=65536,t=3,p=4$placeholder$placeholder",
    role: "admin",
    isActive: true,
  });
  console.log("✅ Admin kullanıcı oluşturuldu");

  // 3. Mali yıl oluştur (2026)
  const fiscalYearId = randomUUID();
  await db.insert(fiscalYears).values({
    id: fiscalYearId,
    tenantId,
    year: 2026,
    startDate: new Date("2026-01-01"),
    endDate: new Date("2026-12-31"),
    isClosed: false,
    isCurrent: true,
  });
  console.log("✅ Mali yıl 2026 oluşturuldu");

  // 4. Tekdüzen Hesap Planı seed
  const accountEntries = TEKDUZEN_HESAP_PLANI.map((acc) => {
    // Parent bulma: kod uzunluğuna göre
    let parentCode: string | null = null;
    if (acc.code.includes(".")) {
      parentCode = acc.code.split(".").slice(0, -1).join(".");
    } else if (acc.code.length > 1) {
      parentCode = acc.code.slice(0, -1);
    }

    return {
      code: acc.code,
      name: acc.name,
      type: acc.type,
      level: acc.level,
      parentCode,
    };
  });

  // Hesapları sırayla oluştur (parent referansları için)
  const codeToId = new Map<string, string>();

  for (const entry of accountEntries) {
    const id = randomUUID();
    codeToId.set(entry.code, id);

    const parentId = entry.parentCode ? codeToId.get(entry.parentCode) ?? null : null;

    await db.insert(accounts).values({
      id,
      tenantId,
      code: entry.code,
      name: entry.name,
      type: entry.type,
      level: entry.level,
      parentId,
      isSystem: true,
      isActive: true,
    });
  }
  console.log(`✅ ${accountEntries.length} hesap planı kaydı oluşturuldu`);

  await client.end();
  console.log("🎉 Seed tamamlandı!");
}

seed().catch((err) => {
  console.error("Seed hatası:", err);
  process.exit(1);
});
